### ISSUE TITLE
Turn off bill acceptor

### ISSUE THREAD

**Issue by Spyspyspy** [Kopachris/py-id003#2]
Hi! I'm trying to implement id003 protocol. Can you help me? I turn bill acceptor to idle state. It accepts/rejects bills, but i want to turn off poll thread and turn of lights. How can I do it?

**Comment by Kopachris** [comment]
You can disable bill acceptance by sending the bill acceptor a set inhibit command (command 0xC3 with data 0x01 to disable the bill acceptor, and data 0x00 to enable it again). The BillVal class in this Python module doesn't have a specific method to do this, just call `send_command(0xC3, b'\x01')` to disable and `send_command(0xC3, b'\x00')` to enable again.

To turn off the bezel lights or shut off the bill acceptor entirely, you'll have to come up with a hardware solution to cut power to the bezel lights or the bill acceptor.

**Comment by Spyspyspy** [comment]
Thanks
