### ISSUE TITLE
BV rejects 200 and 500 euro bills

### ISSUE THREAD

**Issue by Spyspyspy** [Kopachris/py-id003#3]
I'm running test.py, and when i put 200 or 500 euro bill into validator, it rejects it. When do I need to send some specific data to validator, to enable accepting of these bills? And what data?

**Comment by Kopachris** [comment]
Unfortunately, I don't have documentation from JCM regarding non-US bill acceptor firmware, and I have no plans to include support for non-US software in this version of py-id003 as I'm in the middle of a complete rewrite.

You'll have to contact JCM for support. I have no affiliation with them.
